%YAML 1.2
---

# Data filepath
Output_Filepath: "/home/leiwh/Research/Data/RobotGroup/20251125/03/rosbag"          # The rosbag after conversion
ROSBag_FilePath: "/media/leiwh/T7/01_RobotGroup/02_Data/Robot/20251125/03/raw"      # The raw rosbag
ROSBag_FileName: 
  - Intel.bag
GNSSRoveObs_FilePath: "/media/leiwh/T7/01_RobotGroup/02_Data/Robot/20251125/03/raw/fp-6d9d0a_2025-11-25-03-37-56_maximal_gnss1.ubx"   # GNSS rove observation data (ubx|rtcm3|obs)
GNSSRoveEph_FilePath: ""   # GNSS rove ephemeris data (ubx|obs)
GNSSBaseObs_FilePath: "/media/leiwh/T7/01_RobotGroup/02_Data/Robot/20251125/BaseStation/20251125.25o"          # GNSS base observation data (ubx|rtcm3|obs)
GNSSBaseEph_FilePath: "/media/leiwh/T7/01_RobotGroup/02_Data/Robot/20251125/BaseStation/20251125.25p"          # GNSS base ephemeris data (ubx|obs)
GNSSolution_FilePath: "/home/leiwh/Research/Data/RobotGroup/20251125/03/result/R_RTK/gnss_data_1.pos"          # GNSS position solution

# ROS topic before convertion
Imu_Topic_Input: "/camera/imu"                                 # Imu data topic
Image_Topic_Input: "/camera/color/image_raw/compressed"        # Image data topic
GNSSRaw_Topic_Input: ""                                        # The GNSS solution data topic
GNSSSol_Topic_Input: ""                                        # The GNSS solution data topic

# ROS topic after convertion
Imu_Topic_Output: "/Intel/imu/data"                            # Imu data topic
Image_Topic_Output: "/Intel/image/data"                        # Image data topic
GNSSRoveObs_Topic_Output: "/gnss/obs/rove"                     # The GNSS observation data topic [rove station, base station]
GNSSBaseObs_Topic_Output: "/gnss/obs/base"                     # The GNSS observation data topic [rove station, base station]
GNSSRoveEph_Topic_Output: "/gnss/nav/rove"                     # The GNSS ephemeris data topic [rove station, base station]
GNSSBaseEph_Topic_Output: "/gnss/nav/base"                     # The GNSS ephemeris data topic [rove station, base station]
GNSSSol_Topic_Output: "/gnss/solution"                         # The GNSS solution data topic

# Data format
# 0: ROS | 1: VisionRTK_01 | 2: VisionRTK_02 | 3: KAIST | 4: RobotGVINS | 5: TUM | 6: IPS | 7: Intel D457
DataFormat_Input: 7                                            # Data format before conversion
DataFormat_Output: 4                                           # Data format after conversion