%YAML 1.2
---

# Data filepath
Output_Filepath: "/home/leiwh/Research/Document/Paper_SRKF/Data/2023-09-25-03-01-32_maximal/rosbag"           # The filepath to output converted rosbag
ROSBag_FilePath: "/home/leiwh/Research/Document/Paper02/Version-02/Data/2023-09-25-03-01-32_maximal/rosbag"   # The filepath to extract raw rosbag
ROSBag_FileName: 
  - vrtk_6d9d0a_maximal_2023-09-25-03-01-32_0.bag
  - vrtk_6d9d0a_maximal_2023-09-25-03-01-32_1.bag
  - vrtk_6d9d0a_maximal_2023-09-25-03-01-32_2.bag
GNSSBaseObs_FilePath: "/home/leiwh/Research/Document/MasterThesis/Example_05/Data/2023-09-25-03-01-32_maximal/gnss-sins/IGS000USA_R_20232680000_01D_01S_MO.rnx"  # The filepath to read ground truth
GNSSBaseEph_FilePath: "/home/leiwh/Research/Document/MasterThesis/Example_05/Data/2023-09-25-03-01-32_maximal/gnss-sins/IGS000USA_R_20232680000_01D_01S_MN.rnx"  # The filepath to output result
GNSSolution_FilePath: "/home/leiwh/Research/Document/Paper02/Version-02/Data/2023-09-25-03-01-32_maximal/result/ForPaper02/R_RTK/gnss_data_1.pos"    # The filepath to output log information

# ROS topic before convertion
Imu_Topic_Input: "/imu/data"                                   # Imu data topic
Image_Topic_Input: "/camera/lowres/image"                      # Image data topic
GNSSRaw_Topic_Input: "/gnss1/raw"                              # The GNSS solution data topic
GNSSSol_Topic_Input: "/gnss1/status"                           # The GNSS solution data topic

# ROS topic after convertion
Imu_Topic_Output: "/imu/data"                                  # Imu data topic
Image_Topic_Output: "/image/data"                              # Image data topic
GNSSRoveObs_Topic_Output: "/gnss/obs/rove"                     # The GNSS observation data topic [rove station, base station]
GNSSBaseObs_Topic_Output: "/gnss/obs/base"                     # The GNSS observation data topic [rove station, base station]
GNSSRoveEph_Topic_Output: "/gnss/nav/rove"                     # The GNSS ephemeris data topic [rove station, base station]
GNSSBaseEph_Topic_Output: "/gnss/nav/base"                     # The GNSS ephemeris data topic [rove station, base station]
GNSSSol_Topic_Output: "/gnss/solution"                         # The GNSS solution data topic

# Data format
# 0: ROS | 1: VisionRTK_01 | 2: VisionRTK_02 | 3: KAIST | 4: RobotGVINS | 5: TUM | 6: IPS
DataFormat_Input: 1                                            # Data format before conversion
DataFormat_Output: 4                                           # Data format after conversion